[log]
  level = "DEBUG"

[accessLog]

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.tls]

  [entryPoints.backend]
    address = ":8081"

  [entryPoints.pgadmin]
    address = ":5433"

[certificatesResolvers.myresolver.acme]
  email = "kazmierczak.kamil1996@gmail.com"
  storage = "/letsencrypt/acme.json"

  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  watch = true
  exposedByDefault = true
