version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.4
    steps:
      - checkout
      - run: java --version
  deploy-job:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "77:eb:20:91:4d:f9:2f:5c:d7:44:a9:31:04:cb:6d:86"
      - run:
          name: Deploy Over SSH
          command: |
            ssh kmilo@kmilo.me;
            cd /home/kmilo/apps/chatilo;
            ./deploy.sh;

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: develop